---
name: PellesC MSYS2
description: Setup Pelles C with MSYS2 for CMake
inputs:
  cache:
    required: false
    description: If caching should be used
    default: true
  cmake-module:
    required: false
    description: Check PellesC modules, install, if not
    default: check
  env-workaround:
    required: false
    description: Short File Name (SFN) in PATH and environments variables
    default: false
  location:
    required: false
    description: Where to install Pelles C
    default: c:\pellesc
  msystem:
    required: false
    description: >-
      Variant of the environment to set by default: msys, mingw32, mingw64,
      ucrt64, clang64, clangarm64 or skip
    default: mingw64
  verbose:
    required: false
    description: >-
      Show version and location `pocc`, `make`,
      `cmake` ... form PATH. ['off', 'on']
    default: false
  version:
    required: false
    description: >-
      A specific version to install. Defaults to GitHub mirrored.
    default: '13.01-git-lfs'

runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ endsWith(inputs.version, '-git-lfs') ||
              'no' != inputs.cmake-module }}
      uses: actions/checkout@v6

    - name: GitHub LFS pull
      if: ${{ endsWith(inputs.version, '-git-lfs') }}
      shell: pwsh
      run: git lfs pull

    - name: Setup MSYS2
      if: ${{ 'skip' != inputs.msystem }}
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ inputs.msystem }}
        cache: ${{ inputs.cache }}
        pacboy: >-
          binutils:p
          cmake:p
          make:p

    - name: MSYS2 PATH
      if: ${{ 'skip' != inputs.msystem }}
      shell: pwsh
      run: |
        $base = "${{ steps.msys2.outputs.msys2-location }}"
        $msys = "${{ inputs.msystem }}".ToLower()
        if ($${{ fromJSON(inputs.verbose) }}) {
          "MSYS2 PATH:"
          "base=$base"
          "msys=$msys"
          "MSYSTEM=$env:MSYSTEM"
          "PATH=$env:PATH"
          "---"
        }
        "$base\usr\bin`n" + `
        "$base\$msys\bin`n" `
          | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if ("" -eq "$env:MSYSTEM") {
          "MSYSTEM=" + $msys.ToUpper() `
            | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }

    - name: Install CMake PellesC modules
      if: ${{ 'no' != inputs.cmake-module }}
      shell: pwsh -File {0}
      run: |
        if ("always" -eq "${{ inputs.cmake-module }}") {
          cmake -P PellesC\uninstall.cmake
          cmake -P PellesC\install.cmake
        } else {
          cmake -P PellesC\detect.cmake
          if (0 -ne $LASTEXITCODE) {
            cmake -P PellesC\install.cmake
          }
        }
        cmake -P PellesC\detect.cmake
        if ($${{ fromJSON(inputs.verbose) }}) {
          "inputs.cmake-module: ${{ inputs.cmake-module }}"
          "---"
        }

    - name: Pelles C directory and key
      id: pd
      shell: pwsh
      run: |
        $key = "PellesC_${{ inputs.version }}_"
        if ("" -eq "${{ inputs.location }}") {
          $pd = "C:\Program Files\PellesC"
          $sa = ""
          $ia = ""
          $key += "default"
        } else {
          $pd = "${{ inputs.location }}"
          $sa = "/D=$pd"
          $ia = "--install-arguments=$sa"
          $key += $pd -replace "[^a-z]", ""
        }
        mkdir "$pd"
        <# TODO: probably don't needed?
          if ($${{ fromJSON(inputs.env-workaround) }}) {
            $key += "_SFN"
          }
          $key += "_${{ runner.os }}"
         #>
        "pd=$pd`n" + `
        "sa=$sa`n" + `
        "ia=$ia`n" + `
        "key=$key`n"
          | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Restore cached Pelles C directory
      id: cache-pd
      uses: actions/cache/restore@v5
      with:
        key: ${{ steps.pd.outputs.key }}
        path: ${{ steps.pd.outputs.pd }}

    - name: Install Pelles C
      if: steps.cache-pd.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        $setup = "dist\${{ inputs.version }}\setup.exe"
        if (Test-Path -Path "$setup" -PathType Leaf) {
          $shasum = (Get-FileHash $setup)
          if ($${{ fromJSON(inputs.verbose) }}) {
            $shasum
          }
          if ( `
          '84E586D1FCA7B9FEC55BD294A103AF16A045D1DF1BCB77A3F4FDF13D8F239141' `
              -ne $shasum.Hash) {
            "`"$setup`": corrupted"
            TODO-Fail
          }
          Start-Process "$setup" "/S ${{ steps.pd.outputs.sa }}" `
                        -Wait -Verb runas
        } else {
          choco install --yes --no-progress pelles-c `
                --version=${{ inputs.version }} ${{ steps.pd.outputs.ia }}
        }

    - name: Save cached Pelles C directory
      if: steps.cache-pd.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.pd.outputs.key }}
        path: ${{ steps.pd.outputs.pd }}

    - name: Pelles C environments variables
      shell: pwsh
      run: |
        cmd.exe /c "`"${{ steps.pd.outputs.pd }}\Bin\povars64.bat`" && set" | `
          .{process{
            if ($_ -match '^((pellescdir|include|lib|path)[^=]*)=(.*)') {
              Set-Variable ("pd_" + $matches[1]) $matches[3]
            }
          }}
        $pd_path = $pd_path.Substring(0, $pd_path.IndexOf(';'))
        if ($${{ fromJSON(inputs.env-workaround) }}) {
          $pd_pellescdir_sfn = (cmdi.exe /c `
                                "@for %I in (`"$pd_pellescdir`") do @echo %~sI")
          $pd_path = $pd_path.Replace($pd_pellescdir, $pd_pellescdir_sfn, `
                                      'OrdinalIgnoreCase')
          $pd_lib = $pd_lib.Replace($pd_pellescdir, $pd_pellescdir_sfn, `
                                    'OrdinalIgnoreCase')
          $pd_include = $pd_include.Replace($pd_pellescdir, `
                                            $pd_pellescdir_sfn, `
                                            'OrdinalIgnoreCase')
          $pd_pellescdir = $pd_pellescdir_sfn
        }
        "PellesCDir=$pd_pellescdir`n" + `
        "INCLUDE=$pd_include`n" + `
        "LIB=$pd_lib`n" `
          | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "$pd_path`n" `
          | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Show version
      if: ${{ fromJSON(inputs.verbose) }}
      shell: pwsh
      run: |
        "PATH=$env:PATH"
        "---"
        "PellesCDir=$env:PellesCDir"
        "INCLUDE=$env:INCLUDE"
        "LIB=$env:LIB"
        get-command pocc
        pocc | Select-Object -First 1
        if ("skip" -ne "${{ inputs.msystem }}") {
          "MSYSTEM=$env:MSYSTEM"
          get-command pacman
          pacman -V  | Select-Object -First 2
        }
        foreach ($prg in 'ar', 'make', 'cmake', 'choco') {
          try {
            get-command $prg
            &$prg --version | Select-Object -First 1
          } catch {}
        }
        dir "$env:PellesCDir"
        type "$env:PellesCDir/Bin/povars64.bat"
