---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)
#
# This starter workflow is for a CMake project running on multiple platforms.
# There is a different starter workflow if you just want a single platform.
# See:
# https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: CMake on multiple platforms

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all
      # matrix combinations. Consider changing this to true when your workflow
      # is stable.

      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      #
      # 1. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2025-vs2026, "MSYS Makefiles">
      #
      # 2. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2025, "MSYS Makefiles"> (windows-latest at 26.02.2026)
      #
      # 3. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2022, "MSYS Makefiles">
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.)
      # customize the build_type list.

      matrix:
        os: [windows-latest]
        c_compiler: [cc]
        build_type: [Release]
        # TODO: c_compiler: [pocc]
        # TODO: os: [windows-2025-vs2026, windows-2025, windows-2022]
        include:
          - c_compiler: cc
            generator: "MSYS Makefiles"
            platform: "win32"

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install python module
        run: |
          python -c "import sys; print(sys.version); print(sys.executable)"
          python -m pip install yamllint

      - name: Lint
        run: |
          python -m yamllint --list-file .
          python -m yamllint .

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into
        # step outputs. These step outputs can be used throughout the workflow
        # file.

        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" \
               >> "$GITHUB_OUTPUT"

      - name: Test action (Setup PellesC with pre-installed MSYS2 for CMake)
        uses: ./
        with:
          # version: 12.0.2
          verbose: true

      - name: Check workaround Pelles C long name bug in `cc`
        shell: pwsh -File {0}
        run: |
          $exitcode = 0
          cc hello.c
          if ($LASTEXITCODE) {
            $exitcode = $LASTEXITCODE
            "`"cc hello.c`": FAIL $LASTEXITCODE"
          }
          &"$env:PellesCDirLong\Bin\cc.exe" hello.c
          if ($LASTEXITCODE) {
            "`"$env:PellesCDirLong\Bin\cc.exe hello.c`": Expected $LASTEXITCODE"
          } else {
            $exitcode = 1
          }
          &"$env:PellesCDir\Bin\cc.exe" hello.c
          if ($LASTEXITCODE) {
            $exitcode = $LASTEXITCODE
            "`"$env:PellesCDir\Bin\cc.exe hello.c`": FAIL $LASTEXITCODE"
          }
          del hello.obj
          $LASTEXITCODE = $exitcode

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only
        # required if you are using a single-configuration generator such as
        # make.  See
        # https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type

        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER="$env:PellesCDir\Bin\cc.exe"
          -G "${{ matrix.generator }}"
          -S ${{ github.workspace }}
          ${{ matrix.cmake_add }}

      - name: Build
        # Build your program with the given configuration. Note that --config
        # is needed because the default Windows generator is a multi-config
        # generator (Visual Studio generator).

        run: >
          cmake --build ${{ steps.strings.outputs.build-output-dir }}
          --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        # Execute tests defined by the CMake configuration. Note that
        # --build-config is needed because the default Windows generator is a
        # multi-config generator (Visual Studio generator).  See
        # https://cmake.org/cmake/help/latest/manual/ctest.1.html for more
        # detail

        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}

      - name: Run Windows
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        if: ${{ matrix.platform == 'win32' }}
        run: |
          ./hello
          ./bsd_echo my args
