---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)
#
# This starter workflow is for a CMake project running on multiple platforms.
# There is a different starter workflow if you just want a single platform.
# See:
# https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml

name: CMake on multiple platforms

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all
      # matrix combinations. Consider changing this to true when your workflow
      # is stable.

      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      #
      # 1. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2025-vs2026, "MSYS Makefiles">
      #
      # 2. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2025, "MSYS Makefiles"> (windows-latest at 26.02.2026)
      #
      # 3. <Latest PellesC compiler toolchain on the default runner image,
      # windows-2022, "MSYS Makefiles">
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.)
      # customize the build_type list.

      matrix:
        version: [13.01-git-lfs, 12.0.2]  # , 11.0.2]
        build_type: [Release]
        generator: ["MSYS Makefiles"]
        platform: ["win32"]
        cmake_add: ["--debug-trycompile"]
        include:
          - version: 13.01-git-lfs
            c_compiler: cc
            os: windows-2025
          - version: 12.0.2
            c_compiler: pocc
            os: windows-2022
            # - version: 11.0.2
            #   c_compiler: pocc
            #   os: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v6

      - name: Lint
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          python -m yamllint .

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into
        # step outputs. These step outputs can be used throughout the workflow
        # file.

        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" \
               >> "$GITHUB_OUTPUT"

      - name: Test action (Setup PellesC with pre-installed MSYS2 for CMake)
        uses: ./
        with:
          location:  # Default of installer: `C:\Program Files\PellesC`
          env-workaround: true  # Needed workaround
          version: ${{ matrix.version }}
          verbose: true

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only
        # required if you are using a single-configuration generator such as
        # make.  See
        # https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type

        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} `
            ${{ (matrix.c_compiler &&
                 format('-DCMAKE_C_COMPILER={0}', matrix.c_compiler)) || '' }} `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -G "${{ matrix.generator }}" `
            -S "${{ github.workspace }}" `
            ${{ matrix.cmake_add }}

      - name: Build
        # Build your program with the given configuration. Note that --config
        # is needed because the default Windows generator is a multi-config
        # generator (Visual Studio generator).

        run: >
          cmake --build ${{ steps.strings.outputs.build-output-dir }}
          --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        # Execute tests defined by the CMake configuration. Note that
        # --build-config is needed because the default Windows generator is a
        # multi-config generator (Visual Studio generator).  See
        # https://cmake.org/cmake/help/latest/manual/ctest.1.html for more
        # detail

        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}

      - name: Run Windows
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        if: ${{ matrix.platform == 'win32' }}
        run: |
          ./hello
          ./bsd_echo my args
