---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

name: CMake on multiple platforms

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        version: [11.0.2, 12.0.2, 13.01-git-lfs, 14.0-rc1-git-lfs]
        os: [windows-latest, windows-2022]
        c_compiler: ['', pocc]
        build_type: [Release]
        generator: ["MSYS Makefiles"]
        # cmake_add: [--debug-trycompile]
        exclude:
          - {version: 11.0.2, os: windows-latest}
          - {version: 11.0.2, c_compiler: ''}
          - {version: 12.0.2, os: windows-latest}
        include:
          - version: 13.01-git-lfs
            os: windows-latest
            c_compiler: cc  # One test without `-DCMAKE_C_COMPILER=...`
            build_type: Release
            generator: "MSYS Makefiles"

    steps:
      - uses: actions/checkout@v6

      - name: Lint
        if: matrix.c_compiler == ''
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          python -m yamllint .

      - name: Test action (Setup PellesC with pre-installed MSYS2 for CMake)
        uses: ./
        with:
          version: ${{ matrix.version }}
          verbose: true
          # location:  # Default of installer: `C:\Program Files\PellesC`
          # env-workaround: true  # Needed workaround
          # cmake-update: true
          # install: patch
          # pacboy: clang:p

      - name: Check compiler
        run: |
          if ("" -eq "${{ matrix.c_compiler }}") {
            $cc = "cc"
          } else {
            $cc = "${{ matrix.c_compiler }}"
          }
          &$cc hello.c
          if ("cc" -ne $cc) {
            polink hello.obj
          }
          .\hello.exe
          del hello.obj,hello.exe

      - name: Configure CMake
        run: |
          cmake -B build `
            ${{ case(matrix.c_compiler == '', '',
                format('-DCMAKE_C_COMPILER={0}', matrix.c_compiler)) }} `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -G "${{ matrix.generator }}" `
            -S . `
            ${{ matrix.cmake_add }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
          --test-dir build

      - name: Run Windows
        run: |
          cd build
          ./hello
          ./bsd_echo my args
